export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "lightblue", padding: '1rem' }}>
          <h2>Header page</h2>
        </header>
        {children}
        <footer style={{ backgroundColor: 'ghostwhite', padding: "1rem" }}>
          <h2>Footer page</h2>
        </footer>
        <Footer1/>
      </body>
    </html>
  )
}
