import { Footer1 } from "../components/footer1";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "lightblue", padding: '1rem' }}>
          <h2>Header Page</h2>
        </header>
        <main>
          {children}
        </main>
        <footer style={{ backgroundColor: 'ghostwhite', padding: "1rem" }}>
          <h2>Footer Page</h2>
          <Footer1/>
        </footer>
      </body>
    </html>
  );
}
