import React from "react";

export const metadata = {
  // title: 'Next.js',
  // description: 'Generated by Next.js',
  //Title metadata implementation
  //Default title for whole page if there is no such title
  //Template title will add %s title from children and like for blog page 'Blog | Template title'
  //Abosolute will be same for all page if there is no such title in the children page
  title: {
    absolute: "Absolute title",
    default: "Next.js learning",
    template: "%s | Template title"
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "lightblue", padding: '1rem' }}>
          <h2>Header Page</h2>
        </header>
        <main>
          {children}
        </main>
        <footer style={{ backgroundColor: 'ghostwhite', padding: "1rem" }}>
          <h2>Footer Page</h2>
        </footer>
      </body>
    </html>
  );
}
